// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rarefy_beta_cpp
Rcpp::List rarefy_beta_cpp(Rcpp::S4 mat, int depth, int n_iter, Rcpp::CharacterVector beta_metrics, Rcpp::CharacterVector unifrac_metrics, Rcpp::RObject phylo, Rcpp::RObject row_to_tip_obj, double unifrac_alpha, int n_threads, double seed, int kernel);
RcppExport SEXP _metagMisc2_rarefy_beta_cpp(SEXP matSEXP, SEXP depthSEXP, SEXP n_iterSEXP, SEXP beta_metricsSEXP, SEXP unifrac_metricsSEXP, SEXP phyloSEXP, SEXP row_to_tip_objSEXP, SEXP unifrac_alphaSEXP, SEXP n_threadsSEXP, SEXP seedSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type beta_metrics(beta_metricsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type unifrac_metrics(unifrac_metricsSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type phylo(phyloSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type row_to_tip_obj(row_to_tip_objSEXP);
    Rcpp::traits::input_parameter< double >::type unifrac_alpha(unifrac_alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(rarefy_beta_cpp(mat, depth, n_iter, beta_metrics, unifrac_metrics, phylo, row_to_tip_obj, unifrac_alpha, n_threads, seed, kernel));
    return rcpp_result_gen;
END_RCPP
}
// rarefy_alpha_cpp
Rcpp::List rarefy_alpha_cpp(Rcpp::S4 mat, Rcpp::IntegerVector depths, int n_iter, Rcpp::LogicalVector count_mask, Rcpp::LogicalVector phylo_mask, Rcpp::RObject phylo, Rcpp::RObject row_to_tip_obj, int n_threads, double seed, int kernel);
RcppExport SEXP _metagMisc2_rarefy_alpha_cpp(SEXP matSEXP, SEXP depthsSEXP, SEXP n_iterSEXP, SEXP count_maskSEXP, SEXP phylo_maskSEXP, SEXP phyloSEXP, SEXP row_to_tip_objSEXP, SEXP n_threadsSEXP, SEXP seedSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type depths(depthsSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type count_mask(count_maskSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type phylo_mask(phylo_maskSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type phylo(phyloSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type row_to_tip_obj(row_to_tip_objSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(rarefy_alpha_cpp(mat, depths, n_iter, count_mask, phylo_mask, phylo, row_to_tip_obj, n_threads, seed, kernel));
    return rcpp_result_gen;
END_RCPP
}
// rarefy_single_matrix_cpp
Rcpp::S4 rarefy_single_matrix_cpp(Rcpp::S4 mat, int depth, double seed, int kernel);
RcppExport SEXP _metagMisc2_rarefy_single_matrix_cpp(SEXP matSEXP, SEXP depthSEXP, SEXP seedSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(rarefy_single_matrix_cpp(mat, depth, seed, kernel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_metagMisc2_rarefy_beta_cpp", (DL_FUNC) &_metagMisc2_rarefy_beta_cpp, 11},
    {"_metagMisc2_rarefy_alpha_cpp", (DL_FUNC) &_metagMisc2_rarefy_alpha_cpp, 10},
    {"_metagMisc2_rarefy_single_matrix_cpp", (DL_FUNC) &_metagMisc2_rarefy_single_matrix_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_metagMisc2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
